name: Snyk Infrastructure as Code Scan
on: [push, pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: install aws-cdk cli, install dependencies and finally cdk synth
        run: |
          npm install --location=global aws-cdk
          cdk synth
      - name: Run IaC test for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --report
